cmds: add tp to vehicle id admin command
SA-MP-Developer/SemiRP pull request #25
Opened 2020-05-06 10:30 UTC by DuboisS

2020-05-06 10:59 UTC, V1ck3s requested changes
Good, there is just one small thing to fix.

2020-05-06 10:59 UTC, vic1997 commented on SemiRP/Utils/AdminUtils/AdminHelper.cs
> +            var vehicle = (Vehicle)Vehicle.Find(id);
No need to cast here, use Vehicle type directly
```suggestion
            Vehicle vehicle = Vehicle.Find(id);
```

2020-05-06 12:49 UTC, V1ck3s approved these changes

2020-05-06 20:01 UTC, Papawy reviewed
There is some mistakes due to our coding standards for this codebase, but otherwise it is good.

2020-05-06 20:01 UTC, Papawy commented on SemiRP/Commands/AdminCommands.cs
> +            [Command("tpn", "tpnearest")]
We should always but the full command name in first position.

2020-05-06 20:01 UTC, Papawy commented on SemiRP/PermissionList.cs
> +            "admin.cmds.vehicule.tpid",
Just put `admin.cmds.vehicule.tp` not `tpid`.

2020-05-07 16:52 UTC, Papawy commented
Squash your commits @DuboisS .

2020-05-07 19:17 UTC, merged